"""Pure rule contracts and deterministic evaluators for Kuiyo."""

from kuiyo_rules.clauses import ClauseTrace, RuleClauseReference
from kuiyo_rules.contracts import (
    CandidateEvaluationInput,
    CandidateEvaluationOutput,
    CandidateTierInput,
    CandidateTierOutput,
    OpeningCandidateGenerateInput,
    OpeningCandidateGenerateOutput,
    build_evaluation_input,
    build_generate_input,
    build_tier_input,
    candidate_handoff_from_output,
    candidate_handoff_from_frame,
    canonical_candidate_handoff,
    canonical_evaluation_handoff,
    evaluation_handoff_from_output,
)
from kuiyo_rules.definitions import ResearchRuleDefinition, ResearchRuleVersion
from kuiyo_rules.evaluation import (
    evaluate_opening_candidates,
    generate_opening_candidates,
    tier_opening_candidates,
)
from kuiyo_rules.evidence import (
    ContentEvidence,
    InputEvidence,
    KnownTimeConformance,
    QueryIntent,
    ResolvedSourceEvidence,
    dataframe_fingerprint,
    input_evidence_semantic_fingerprint,
    input_evidence_semantic_payload,
    semantic_fingerprint,
    typed_rule_contract_fingerprint,
)
from kuiyo_rules.execution import canonical_attempt_key
from kuiyo_rules.registry import (
    RuleSpec,
    RuleStageSpec,
    evaluate_rule,
    get_rule_spec,
    get_rule_version,
)

__all__ = [
    "CandidateEvaluationInput",
    "CandidateEvaluationOutput",
    "CandidateTierInput",
    "CandidateTierOutput",
    "ClauseTrace",
    "ContentEvidence",
    "InputEvidence",
    "KnownTimeConformance",
    "OpeningCandidateGenerateInput",
    "OpeningCandidateGenerateOutput",
    "build_evaluation_input",
    "build_generate_input",
    "build_tier_input",
    "candidate_handoff_from_output",
    "candidate_handoff_from_frame",
    "canonical_candidate_handoff",
    "canonical_evaluation_handoff",
    "evaluation_handoff_from_output",
    "QueryIntent",
    "ResolvedSourceEvidence",
    "ResearchRuleDefinition",
    "ResearchRuleVersion",
    "RuleClauseReference",
    "RuleSpec",
    "RuleStageSpec",
    "evaluate_opening_candidates",
    "evaluate_rule",
    "get_rule_spec",
    "get_rule_version",
    "generate_opening_candidates",
    "dataframe_fingerprint",
    "canonical_attempt_key",
    "input_evidence_semantic_fingerprint",
    "input_evidence_semantic_payload",
    "semantic_fingerprint",
    "tier_opening_candidates",
    "typed_rule_contract_fingerprint",
]
